# Generated by Django 3.0.7 on 2020-06-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('CG', 'Convenience Goods'), ('SHG', 'Shopping Goods'), ('SG', 'Specialty Goods')], max_length=50)),
                ('picture', models.ImageField(upload_to='products/images')),
                ('amount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('is_new', models.BinaryField(default=False)),
                ('certificate', models.FileField(upload_to='products/files')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2)),
                ('view_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
