# Generated by Django 3.0.7 on 2020-06-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='products',
            table='company_products',
        ),
    ]
