# Generated by Django 3.0.7 on 2020-06-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTask', '0003_car_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelsTask.Manufacturer', verbose_name='Manufacturer'),
        ),
    ]
