# Generated by Django 3.0.7 on 2020-06-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsTask', '0007_author_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='books',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
